// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	UserEmail    string             `json:"user_email"`
	UserName     string             `json:"user_name"`
	Claims       []byte             `json:"claims"`
	RefreshToken string             `json:"refresh_token"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}
