// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, user_id, user_email, user_name, claims, refresh_token, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, user_email, user_name, claims, refresh_token, created_at, last_seen_at, expires_at
`

type CreateSessionParams struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	UserEmail    string             `json:"user_email"`
	UserName     string             `json:"user_name"`
	Claims       []byte             `json:"claims"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.UserEmail,
		arg.UserName,
		arg.Claims,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.Claims,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, user_email, user_name, claims, refresh_token, created_at, last_seen_at, expires_at FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.Claims,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions
SET id = $1,
    refresh_token = $2,
    expires_at = $3,
    last_seen_at = now()
WHERE id = $4
RETURNING id, user_id, user_email, user_name, claims, refresh_token, created_at, last_seen_at, expires_at
`

type RotateSessionParams struct {
	NewID        string             `json:"new_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	OldID        string             `json:"old_id"`
}

// Rotate the session id and refresh token (e.g. after a token refresh), and
// slide the expiry forward.
func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession,
		arg.NewID,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.OldID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.Claims,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :one
UPDATE sessions
SET last_seen_at = now()
WHERE id = $1
RETURNING id, user_id, user_email, user_name, claims, refresh_token, created_at, last_seen_at, expires_at
`

func (q *Queries) TouchSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, touchSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.Claims,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}
